// Generated by easyeda@0.0.305 from JLCPCB part C62857.
import type { CapacitorProps } from "@tscircuit/props"

export const A_6124B104K500NT = (
  props: Omit<CapacitorProps, "capacitance">,
) => {
  const { name = "C1", ...restProps } = props

  return (
    <capacitor
      name={name}
      capacitance="100nF"
      symbol={
        <symbol>
          <port
            name="pin1"
            pinNumber={1}
            aliases={["1"]}
            direction="left"
            schX={-0.7}
            schY={0.46}
            schStemLength={0.4}
          />
          <port
            name="pin2"
            pinNumber={2}
            aliases={["2"]}
            direction="left"
            schX={-0.7}
            schY={0.16}
            schStemLength={0.4}
          />
          <port
            name="pin3"
            pinNumber={3}
            aliases={["3"]}
            direction="left"
            schX={-0.7}
            schY={-0.14}
            schStemLength={0.4}
          />
          <port
            name="pin4"
            pinNumber={4}
            aliases={["4"]}
            direction="left"
            schX={-0.7}
            schY={-0.44}
            schStemLength={0.4}
          />
          <port
            name="pin5"
            pinNumber={5}
            aliases={["5"]}
            direction="right"
            schX={0.7}
            schY={-0.44}
            schStemLength={0.4}
          />
          <port
            name="pin6"
            pinNumber={6}
            aliases={["6"]}
            direction="right"
            schX={0.7}
            schY={-0.14}
            schStemLength={0.4}
          />
          <port
            name="pin7"
            pinNumber={7}
            aliases={["7"]}
            direction="right"
            schX={0.7}
            schY={0.16}
            schStemLength={0.4}
          />
          <port
            name="pin8"
            pinNumber={8}
            aliases={["8"]}
            direction="right"
            schX={0.7}
            schY={0.46}
            schStemLength={0.4}
          />
          <schematicpath
            points={[
              { x: 0.3, y: -0.64 },
              { x: -0.3, y: -0.64 },
              { x: -0.3, y: 0.66 },
              { x: 0.3, y: 0.66 },
              { x: 0.3, y: -0.64 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.04, y: 0.56 },
              { x: -0.04, y: 0.36 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: 0.56 },
              { x: 0.02, y: 0.36 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.3, y: 0.46 },
              { x: -0.04, y: 0.46 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: 0.46 },
              { x: 0.3, y: 0.46 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.04, y: 0.26 },
              { x: -0.04, y: 0.06 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: 0.26 },
              { x: 0.02, y: 0.06 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.3, y: 0.16 },
              { x: -0.04, y: 0.16 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: 0.16 },
              { x: 0.3, y: 0.16 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.04, y: -0.04 },
              { x: -0.04, y: -0.24 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: -0.04 },
              { x: 0.02, y: -0.24 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.3, y: -0.14 },
              { x: -0.04, y: -0.14 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: -0.14 },
              { x: 0.3, y: -0.14 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.04, y: -0.34 },
              { x: -0.04, y: -0.54 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: -0.34 },
              { x: 0.02, y: -0.54 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: -0.3, y: -0.44 },
              { x: -0.04, y: -0.44 },
            ]}
            strokeColor="#880000"
          />
          <schematicpath
            points={[
              { x: 0.02, y: -0.44 },
              { x: 0.3, y: -0.44 },
            ]}
            strokeColor="#880000"
          />
        </symbol>
      }
      supplierPartNumbers={{
        jlcpcb: ["C62857"],
      }}
      manufacturerPartNumber="6124B104K500NT"
      footprint={
        <footprint>
          <smtpad
            portHints={["pin1"]}
            pcbX="-1.35001mm"
            pcbY="-0.770001mm"
            width="0.7500112mm"
            height="0.7999984mm"
            shape="rect"
          />
          <smtpad
            portHints={["pin8"]}
            pcbX="-1.35001mm"
            pcbY="0.770001mm"
            width="0.7500112mm"
            height="0.7999984mm"
            shape="rect"
          />
          <smtpad
            portHints={["pin2"]}
            pcbX="-0.40005mm"
            pcbY="-0.770001mm"
            width="0.580009mm"
            height="0.7999984mm"
            shape="rect"
          />
          <smtpad
            portHints={["pin7"]}
            pcbX="-0.40005mm"
            pcbY="0.770001mm"
            width="0.580009mm"
            height="0.7999984mm"
            shape="rect"
          />
          <smtpad
            portHints={["pin3"]}
            pcbX="0.40005mm"
            pcbY="-0.770001mm"
            width="0.580009mm"
            height="0.7999984mm"
            shape="rect"
          />
          <smtpad
            portHints={["pin6"]}
            pcbX="0.40005mm"
            pcbY="0.770001mm"
            width="0.580009mm"
            height="0.7999984mm"
            shape="rect"
          />
          <smtpad
            portHints={["pin4"]}
            pcbX="1.35001mm"
            pcbY="-0.770001mm"
            width="0.7500112mm"
            height="0.7999984mm"
            shape="rect"
          />
          <smtpad
            portHints={["pin5"]}
            pcbX="1.35001mm"
            pcbY="0.770001mm"
            width="0.7500112mm"
            height="0.7999984mm"
            shape="rect"
          />
          <silkscreenpath
            route={[
              { x: -2.025015000000053, y: 0.44985939999992297 },
              { x: -2.025015000000053, y: 1.46989799999983 },
              { x: 2.0249896000000263, y: 1.46989799999983 },
              { x: 2.0249896000000263, y: 0.44985939999992297 },
            ]}
          />
          <silkscreenpath
            route={[
              { x: -2.025015000000053, y: -0.4501134000000775 },
              { x: -2.025015000000053, y: -1.4701519999999846 },
              { x: 2.0249896000000263, y: -1.4701519999999846 },
              { x: 2.0249896000000263, y: -0.4501134000000775 },
            ]}
          />
          <silkscreentext
            text="{NAME}"
            pcbX="-0.0127mm"
            pcbY="2.4732mm"
            anchorAlignment="center"
            fontSize="1mm"
          />
          <courtyardoutline
            outline={[
              { x: -2.282000000000039, y: 1.7232000000000198 },
              { x: 2.2566000000000486, y: 1.7232000000000198 },
              { x: 2.2566000000000486, y: -1.7231999999999061 },
              { x: -2.282000000000039, y: -1.7231999999999061 },
              { x: -2.282000000000039, y: 1.7232000000000198 },
            ]}
          />
        </footprint>
      }
      cadModel={{
        objUrl:
          "https://modelcdn.tscircuit.com/easyeda_models/assets/C62857.obj?uuid=8ab5a70e4d364b4c99f72ce3c83a7fcd",
        stepUrl:
          "https://modelcdn.tscircuit.com/easyeda_models/assets/C62857.step?uuid=8ab5a70e4d364b4c99f72ce3c83a7fcd",
        pcbRotationOffset: 0,
        modelOriginPosition: {
          x: 0.04698999999993703,
          y: -0.008000999999921987,
          z: -0.01,
        },
      }}
      {...restProps}
    />
  )
}
