import { parseModelString } from "@tscircuit/modelprinter"
import { assemblyMotorProps } from "@tscircuit/props"
import { PrimitiveComponent } from "../base-components/PrimitiveComponent"
import { renderAssemblyCadModel } from "./render-assembly-cad-model"
import { resolveAssemblyModel } from "./resolve-assembly-model"
import { resolveAssemblyMotorPlacement } from "./resolve-assembly-motor-placement"

export class AssemblyMotor extends PrimitiveComponent<
  typeof assemblyMotorProps
> {
  get config() {
    return { componentName: "AssemblyMotor", zodProps: assemblyMotorProps }
  }

  get motorModelString() {
    return this._parsedProps.model ?? this._parsedProps.standard!
  }

  get motorModel() {
    const model = (() => {
      try {
        return parseModelString(this.motorModelString)
      } catch (cause) {
        throw new Error(
          `assembly.motor "${this.name}" requires a NEMA modelprinter model: ${cause instanceof Error ? cause.message : cause}`,
          { cause },
        )
      }
    })()
    if (model.fn !== "nema") {
      throw new Error(
        `assembly.motor "${this.name}" requires a NEMA modelprinter model`,
      )
    }
    return model
  }

  doInitialSourceRender(): void {
    // Parse the spec even in schematic-only builds. Geometry is generated by
    // jscad-electronics behind modelcdn, never by core or modelprinter.
    this.motorModel
    this.source_component_id = this.root!.db.source_component.insert({
      ftype: "simple_chip",
      name: this.name,
    }).source_component_id
  }

  doInitialCadModelRender(): void {
    if (!this.root || this.root.pcbDisabled || !this.source_component_id) return
    const model = resolveAssemblyModel({ model: this.motorModelString })!
    this.cad_component_id = renderAssemblyCadModel(
      this,
      {
        ...model,
        rotationOffset: resolveMotorRotation(
          this._parsedProps.shaftFacingDirection,
        ),
      },
      resolveAssemblyMotorPlacement(this),
    )
  }
}

/** CAD Euler angles (degrees) rotating the motor-local +Z shaft direction into
 * right-handed circuit world: +X right, +Y top, +Z above. The motor's origin
 * is a point in mm at the shaft-side mounting face, not its bounding-box center.
 */
const resolveMotorRotation = (
  direction: AssemblyMotor["_parsedProps"]["shaftFacingDirection"],
) => {
  switch (direction) {
    case "x+":
      return { x: 0, y: 90, z: 0 }
    case "x-":
      return { x: 0, y: 270, z: 0 }
    case "y+":
      return { x: 270, y: 0, z: 0 }
    case "y-":
      return { x: 90, y: 0, z: 0 }
    case "z-":
      // resolveAssemblyMotorPlacement uses the canonical bottom-side 180° Y
      // rotation in renderAssemblyCadModel, paired with the board-plane flip.
      return { x: 0, y: 0, z: 0 }
    case "z+":
      return { x: 0, y: 0, z: 0 }
  }
}
