import {
  getNemaMotorReferencePoints,
  parseModelString,
} from "@tscircuit/modelprinter"
import { assemblyMotorProps } from "@tscircuit/props"
import { PrimitiveComponent } from "../base-components/PrimitiveComponent"
import { renderAssemblyCadModel } from "./render-assembly-cad-model"
import { resolveAssemblyModel } from "./resolve-assembly-model"
import { resolveAssemblyMotorPlacement } from "./resolve-assembly-motor-placement"
import { resolveAssemblyMotorRotation } from "./resolve-assembly-motor-rotation"
import { resolveMotorFaceMount } from "./resolve-motor-face-mount"

export class AssemblyMotor extends PrimitiveComponent<
  typeof assemblyMotorProps
> {
  get config() {
    return { componentName: "AssemblyMotor", zodProps: assemblyMotorProps }
  }

  get motorModelString() {
    const base = this._parsedProps.model ?? this._parsedProps.standard!
    const wireConnection = this._parsedProps.wireConnection
    if (wireConnection === undefined) return base
    const isJstPh6 = ["jst6_ph", "jst-ph-6", "jst_ph_6"].includes(
      wireConnection,
    )
    return `${base}_${isJstPh6 ? "jstph6" : wireConnection === "none" ? "nowires" : "wirestubs"}`
  }

  get motorModel() {
    const model = (() => {
      try {
        return parseModelString(this.motorModelString)
      } catch (cause) {
        throw new Error(
          `assembly.motor "${this.name}" requires a NEMA modelprinter model: ${cause instanceof Error ? cause.message : cause}`,
          { cause },
        )
      }
    })()
    if (model.fn !== "nema") {
      throw new Error(
        `assembly.motor "${this.name}" requires a NEMA modelprinter model`,
      )
    }
    return model
  }

  get motorReferencePoints() {
    const { fn, ...parameters } = this.motorModel
    return getNemaMotorReferencePoints(parameters)
  }

  doInitialSourceRender(): void {
    // Parse the spec even in schematic-only builds. Geometry is generated by
    // jscad-electronics behind modelcdn, never by core or modelprinter.
    this.motorModel
    this.source_component_id = this.root!.db.source_component.insert({
      ftype: "motor",
      name: this.name,
    }).source_component_id
  }

  doInitialCadModelRender(): void {
    if (!this.root || this.root.pcbDisabled || !this.source_component_id) return
    const model = resolveAssemblyModel({ model: this.motorModelString })!
    const faceMount = resolveMotorFaceMount(this)
    if (faceMount) {
      this.cad_component_id = renderAssemblyCadModel(
        this,
        { ...model, rotationOffset: faceMount.rotation },
        { ...faceMount, pcbRotation: 0, layer: "top" },
      )
      return
    }
    const placement = resolveAssemblyMotorPlacement(this)
    this.cad_component_id = renderAssemblyCadModel(
      this,
      {
        ...model,
        rotationOffset: resolveAssemblyMotorRotation(this, placement),
      },
      placement,
    )
  }
}
