import { expect, test } from "bun:test"
import { Board, Group, Net } from "lib"

test("shared net resolution preserves ordering, type constraints, misses and scope", () => {
  const board = new Board({ width: 10, height: 10 })
  const group = new Group({ name: "ordinary" })
  const nested = new Group({ name: "isolated", subcircuit: true })
  board.addAll([group, nested])
  const hidden = new Net({ name: "POWER" })
  nested.add(hidden)
  expect(board.selectOne("net.POWER")).toBeNull()
  const first = new Net({ name: "POWER ALIAS" })
  const second = new Net({ name: "POWER" })
  group.addAll([first, second])
  expect(board.selectOne<Net>("net.ALIAS", { type: "net" })).toBe(first)
  expect(board.selectOne<Net>("net.POWER")).toBe(first)
  expect(board.selectOne("net.POWER", { type: "port" })).toBeNull()
  expect(board.selectOne("net.POWER", { port: true })).toBeNull()
  expect(board.selectOne<Net>("net.POWER", { type: "net" })).toBe(first)
  expect(nested.selectOne<Net>("net.POWER")).toBe(hidden)
  expect(board.selectOne<Net>('net.POWER[name="POWER"]')).toBe(second)
  group.remove(first)
  expect(board.selectOne<Net>("net.POWER", { type: "net" })).toBe(second)
  expect(board.selectOne("net.ALIAS")).toBeNull()
  board.remove(group)
  expect(board.selectOne("net.POWER")).toBeNull()
  board.add(new Net({ name: "POWER" }))
  expect(board.selectOne<Net>("net.POWER", { type: "net" })).not.toBe(second)
})
