export const orderedRenderPhases = [
  "ReactSubtreesRender",
  "RenderIsolatedSubcircuits",
  "InflateSubcircuitCircuitJson",
  "SourceNameDuplicateComponentRemoval",
  "PcbFootprintStringRender",
  "FetchPartFootprint",
  "ResolveFootprintPinLabels",
  "InitializePortsFromChildren",
  "CreateNetsFromProps",
  "AssignFallbackProps",
  "CreateTracesFromProps",
  "CreateTracesFromNetLabels",
  "CreateTraceHintsFromProps",
  "CreateAutoplacedBreakoutPoints",
  "SourceGroupRender",
  "AssignNameToUnnamedComponents",
  "SourceRender",
  "CheckRefDesConvention",
  "SourceComponentPropertyValidation",
  "SourceParentAttachment",
  "PortMatching",
  "OptimizeSelectorCache",
  "SourceTraceRender",
  "SourceAddConnectivityMapKey",
  "SourceDesignRuleChecks",
  "SimulationRender",
  "SchematicComponentRender",
  "SchematicPortRender",
  "SymbolContainerRender",
  "SchematicPrimitiveRender",
  "SchematicSymbolResize",
  "SchematicComponentSizeCalculation",
  "SchematicLayout",
  "SchematicSectionRender",
  "SchematicTraceRender",
  "SchematicSheetRender",
  "SchematicReplaceNetLabelsWithSymbols",
  "SchematicLabelNetsWithConflictingNames",
  "PanelBoardLayout",
  "ValidatePcbCoordinates",
  "PcbComponentRender",
  "PcbPrimitiveRender",
  "PcbFootprintLayout",
  "PcbPortRender",
  "PcbPortAttachment",
  "PcbComponentSizeCalculation",
  "PcbComponentAnchorAlignment",
  "PcbCalcPlacementResolution",
  "PcbLayout",
  "PcbBoardAutoSize",
  "PanelLayout",
  "PcbFlexRender",
  "PcbAutoplaceBreakoutPoints",
  "PcbTraceHintRender",
  "PcbManualTraceRender",
  "PcbPlacementDesignRuleChecks",
  "PcbTraceRender",
  "PcbRouteNetIslands",
  "PcbTraceTeardropRender",
  "PcbCopperPourRender",
  "PcbViaStitchRender",
  "PcbCopperPourCleanup",
  "PcbDesignRuleChecks",
  "SilkscreenOverlapAdjustment",
  "CadModelRender",
  "PartsEngineRender",
  "PartOrientationAnalysis",
  "SupplierFootprintMismatchWarning",
  "SimulationSpiceEngineRender",
] as const

export type RenderPhase = (typeof orderedRenderPhases)[number]

export const renderPhaseIndexMap = new Map<RenderPhase, number>(
  orderedRenderPhases.map((phase, index) => [phase, index]),
)

// Declare async dependencies between phases where later phases should wait for
// async effects originating in specific earlier phases to complete within the
// current component's subtree.
export const asyncPhaseDependencies: Partial<
  Record<RenderPhase, RenderPhase[]>
> = {
  InflateSubcircuitCircuitJson: ["RenderIsolatedSubcircuits"],
  ResolveFootprintPinLabels: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicComponentRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicPortRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SymbolContainerRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicPrimitiveRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicSymbolResize: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicComponentSizeCalculation: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  SchematicLayout: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicSectionRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicTraceRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicSheetRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SchematicReplaceNetLabelsWithSymbols: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  SchematicLabelNetsWithConflictingNames: [
    "RenderIsolatedSubcircuits",
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "SchematicTraceRender",
  ],
  PcbFootprintLayout: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PcbComponentSizeCalculation: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  PcbLayout: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PcbBoardAutoSize: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PcbTraceHintRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PcbManualTraceRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PcbTraceTeardropRender: ["PcbTraceRender", "PcbRouteNetIslands"],
  PcbCopperPourRender: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "PcbPlacementDesignRuleChecks",
    "PcbTraceRender",
    "PcbRouteNetIslands",
    "PcbTraceTeardropRender",
  ],
  PcbViaStitchRender: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "PcbPlacementDesignRuleChecks",
    "PcbTraceRender",
    "PcbRouteNetIslands",
    "PcbCopperPourRender",
  ],
  PcbPlacementDesignRuleChecks: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  PcbCopperPourCleanup: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "PcbPlacementDesignRuleChecks",
    "PcbTraceRender",
    "PcbRouteNetIslands",
    "PcbCopperPourRender",
    "PcbViaStitchRender",
  ],
  PcbTraceRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PcbRouteNetIslands: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "PcbPlacementDesignRuleChecks",
  ],
  PcbDesignRuleChecks: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "PcbPlacementDesignRuleChecks",
    "PcbTraceRender",
    "PcbCopperPourRender",
    "PcbViaStitchRender",
    "PcbCopperPourCleanup",
  ],
  SilkscreenOverlapAdjustment: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  CadModelRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PartsEngineRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  PartOrientationAnalysis: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "PartsEngineRender",
  ],
  SupplierFootprintMismatchWarning: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
    "PartsEngineRender",
  ],
  SourceAddConnectivityMapKey: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  PcbComponentAnchorAlignment: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  PcbCalcPlacementResolution: [
    "PcbFootprintStringRender",
    "FetchPartFootprint",
  ],
  ValidatePcbCoordinates: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SourceTraceRender: ["PcbFootprintStringRender", "FetchPartFootprint"],
  SourceDesignRuleChecks: ["PcbFootprintStringRender", "FetchPartFootprint"],
}
